extract-endurance-process-smaps: return non-zero when nothing appropriate found

diff --git a/postproc/extract-endurance-process-smaps b/postproc/extract-endurance-process-smaps
--- a/postproc/extract-endurance-process-smaps
+++ b/postproc/extract-endurance-process-smaps
@@ -96,9 +96,9 @@ fi
 
 fgrep -q "Name: $prog" $prog-*.cap
 if [ $? -ne 0 ]; then
-	echo "ERROR: No matches found for program '$prog'!"
+	echo "ERROR: No matches found for program '$prog'!" 1>&2
 	rm $prog-*.cap
-else
-	echo "Information extracted:"
-	ls $prog-*.cap
+	exit 1
 fi
+echo "Information extracted:"
+ls $prog-*.cap
