endurance-snapshot: do not complain about missing xprop
Stop complaining about missing xprop. Just use it if available, and be
silent if not.

diff --git a/measure/endurance-snapshot b/measure/endurance-snapshot
--- a/measure/endurance-snapshot
+++ b/measure/endurance-snapshot
@@ -133,29 +133,25 @@ mkdir -p $path
 if [ $# -gt 1 ]; then
 	echo "- use-case step description"
 	echo "$2" > $path/step.txt
-else
+elif type xprop >/dev/null 2>/dev/null ; then
 	echo "- use-case step description (focused/topmost window)"
-	if type xprop >/dev/null 2>/dev/null ; then
-		check_display
-		# _NET_ACTIVE_WINDOW standard property tells focused window,
-		# WM_CLASS tells the "name" of the application owning that.
-		win=$(xprop -root _NET_ACTIVE_WINDOW)
-		RET=$?
-		if [ $RET -ne 0 ] ; then
-			echo "$script: WARNING, xprop failed with exit code $RET, check \$DISPLAY and \$XAUTHORITY." 1>&2
-			echo "$script: For some platforms, copy of ~/.Xauthority from the user owning the X session is needed." 1>&2
-		else
-			win=$(echo "$win" | cut -s -d'#' -f2)
-			if [ \! -z $win ]; then
-				app=$(xprop -id $win WM_CLASS|cut -s -d'"' -f2)
-				if [ -z "$app" ]; then
-					app=$(xprop -id $win WM_NAME|cut -s -d'"' -f2)
-				fi
-				echo "$app" > $path/step.txt
-			fi
-		fi
+	check_display
+	# _NET_ACTIVE_WINDOW standard property tells focused window,
+	# WM_CLASS tells the "name" of the application owning that.
+	win=$(xprop -root _NET_ACTIVE_WINDOW)
+	RET=$?
+	if [ $RET -ne 0 ] ; then
+		echo "$script: WARNING, xprop failed with exit code $RET, check \$DISPLAY and \$XAUTHORITY." 1>&2
+		echo "$script: For some platforms, copy of ~/.Xauthority from the user owning the X session is needed." 1>&2
 	else
-		echo "$script: WARNING, 'xprop' tool is missing from PATH" 1>&2
+		win=$(echo "$win" | cut -s -d'#' -f2)
+		if [ \! -z $win ]; then
+			app=$(xprop -id $win WM_CLASS|cut -s -d'"' -f2)
+			if [ -z "$app" ]; then
+				app=$(xprop -id $win WM_NAME|cut -s -d'"' -f2)
+			fi
+			echo "$app" > $path/step.txt
+		fi
 	fi
 fi
 
