is step description missing, save topmost/focused app name

diff --git a/measure/save-incremental-endurance-stats b/measure/save-incremental-endurance-stats
--- a/measure/save-incremental-endurance-stats
+++ b/measure/save-incremental-endurance-stats
@@ -61,6 +61,9 @@
 # - Use ifconfig -a so that all present interfaces are always listed.
 #   This way it's easier to track the amounts transferred through them
 #   (Desktop Linux interfaces zero values when they go down, N900 don't)
+# 2010-04-20:
+# - If use-case step description isn't given, add information about
+#   focused / topmost application
 
 script="${0##*/}"
 # incorrect number of arguments or first argument starts with "-"
@@ -133,6 +136,25 @@ mkdir -p $path
 if [ $# -gt 1 ]; then
 	echo "- use-case step description"
 	echo "$2" > $path/step.txt
+else
+	if [ -z $(which xprop) ]; then
+		echo "$script: WARNING, 'xprop' tool is missing from PATH" 1>&2
+	else
+		echo "- focused/topmost window"
+		# _NET_ACTIVE_WINDOW standard property tells focused window,
+		# WM_CLASS tells the "name" of the application owning that
+		win=$(xprop -root _NET_ACTIVE_WINDOW|cut -s -d'#' -f2)
+		app=$(xprop -id $win WM_CLASS|cut -s -d'"' -f2)
+		# Maemo specific property for topmost window
+		win=$(xprop -root _MB_CURRENT_APP_WINDOW|cut -s -d'#' -f2)
+		if [ \! -z "$win" ]; then
+			topmost=$(xprop -id $win WM_CLASS|cut -s -d'"' -f2)
+			if [ "$app" != "$topmost" ]; then
+				app="focused: $app, on top: $topmost"
+			fi
+		fi
+		echo "$app" > $path/step.txt
+	fi
 fi
 
 # save memory statistics
