save-incremental-endurance-stats: check `xmeminfo' availability, redirect output to separate file

diff --git a/measure/save-incremental-endurance-stats b/measure/save-incremental-endurance-stats
--- a/measure/save-incremental-endurance-stats
+++ b/measure/save-incremental-endurance-stats
@@ -116,6 +116,7 @@ if [ $# -lt 1 ] || [ $# -gt 2 ] || [ "${1#-}" != "$1" ]; then
 	echo " - stat         (kernel/system statistics, see proc(5))"
 	echo " - syslog.gz    (compressed syslog contents)"
 	echo " - usage.csv    (/proc info + X resource & disk usage in CSV format)"
+	echo " - xmeminfo     (X server resource usage information)"
 	echo " - xres.log     (XRes related error messages from xmeminfo)"
 	echo " - bmestat      (Battery information from Battery Management Entity)"
 	echo " - cgroups      (Control Group information)"
@@ -131,10 +132,6 @@ fi
 # do some basic sanity checks
 if [ -z $(which proc2csv 2>/dev/null) ]; then
 	echo "$script: ERROR, 'proc2csv' tool is missing from PATH" 1>&2
-	exit 1
-fi
-if [ -z $(which xmeminfo 2>/dev/null) ]; then
-	echo "$script: ERROR, 'xmeminfo' tool is missing from PATH" 1>&2
 	exit 1
 fi
 if [ -z $(which lzop 2>/dev/null) ]; then
@@ -233,14 +230,16 @@ RET=$?
 if [ $RET -ne 0 ]; then
 	echo "$script: WARNING, proc2csv failed with exit code $RET." 1>&2
 fi
-# info on the UI processes X resource usage
-echo "- X resource usage"
-echo >> $usage
-xmeminfo >> $usage 2> $path/xres.log
-RET=$?
-if [ $RET -ne 0 ]; then
-	cat $path/xres.log 1>&2
-	echo "$script: WARNING, xmeminfo failed with exit code $RET, check \$DISPLAY and \$XAUTHORITY." 1>&2
+
+which xmeminfo >/dev/null 2>/dev/null
+if [ $? -eq 0 ] ; then
+	echo "- X resource usage"
+	xmeminfo > $path/xmeminfo 2> $path/xres.log
+	RET=$?
+	if [ $RET -ne 0 ]; then
+		cat $path/xres.log 1>&2
+		echo "$script: WARNING, xmeminfo failed with exit code $RET, check \$DISPLAY and \$XAUTHORITY." 1>&2
+	fi
 fi
 
 echo "- Disk usage"
